apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: rs1
   labels: 
    app: frontend
spec:
   template:
      metadata:
         name: pod1
         labels:
             app: frontend
      spec:
         containers:
         - name: p1 
           image: nginx
   replicas: 3
   selector:
    matchLabels:
       app: frontend
