apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: build-robot
  automountServiceAccountToken: false
  ...
  
## curl -kv https://192.168.10.1/api -H "Authorization: Bearer ey...(TOKEN)"
